// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/eventarc/v1/trigger.proto

package com.google.cloud.eventarc.v1;

public interface DestinationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.eventarc.v1.Destination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Cloud Run fully-managed service that receives the events. The service
   * should be running in the same project of the trigger.
   * </pre>
   *
   * <code>.google.cloud.eventarc.v1.CloudRun cloud_run = 1;</code>
   * @return Whether the cloudRun field is set.
   */
  boolean hasCloudRun();
  /**
   * <pre>
   * Cloud Run fully-managed service that receives the events. The service
   * should be running in the same project of the trigger.
   * </pre>
   *
   * <code>.google.cloud.eventarc.v1.CloudRun cloud_run = 1;</code>
   * @return The cloudRun.
   */
  com.google.cloud.eventarc.v1.CloudRun getCloudRun();
  /**
   * <pre>
   * Cloud Run fully-managed service that receives the events. The service
   * should be running in the same project of the trigger.
   * </pre>
   *
   * <code>.google.cloud.eventarc.v1.CloudRun cloud_run = 1;</code>
   */
  com.google.cloud.eventarc.v1.CloudRunOrBuilder getCloudRunOrBuilder();

  public com.google.cloud.eventarc.v1.Destination.DescriptorCase getDescriptorCase();
}
