// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/eventarc/v1/trigger.proto

package com.google.cloud.eventarc.v1;

public interface EventFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.eventarc.v1.EventFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The name of a CloudEvents attribute. Currently, only a subset of
   * attributes are supported for filtering.
   * All triggers MUST provide a filter for the 'type' attribute.
   * </pre>
   *
   * <code>string attribute = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The attribute.
   */
  java.lang.String getAttribute();
  /**
   * <pre>
   * Required. The name of a CloudEvents attribute. Currently, only a subset of
   * attributes are supported for filtering.
   * All triggers MUST provide a filter for the 'type' attribute.
   * </pre>
   *
   * <code>string attribute = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for attribute.
   */
  com.google.protobuf.ByteString
      getAttributeBytes();

  /**
   * <pre>
   * Required. The value for the attribute.
   * </pre>
   *
   * <code>string value = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * Required. The value for the attribute.
   * </pre>
   *
   * <code>string value = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
